import Foundation

protocol MissionCatalogProviding: Sendable { func missions(for profile: UserProfile?) -> [Mission] }
struct DefaultMissionCatalog: MissionCatalogProviding {
    func missions(for profile: UserProfile?) -> [Mission] { let preferred = profile?.difficultSituations ?? []; return Self.all.sorted { preferred.contains($0.category.difficultSituation) && !preferred.contains($1.category.difficultSituation) } }
    static let all: [Mission] = [
        make("tell-yourself", "Tell me about yourself", .interview, .foundation, "Hiring manager", "Candidate", "A first-round interview", "Give a focused 60-second introduction that connects your experience to the role.", ["State your role or background", "Give one relevant strength", "End with your career direction"], ["Keep it under 90 seconds", "Do not list your full CV"], ["background", "experience", "strength", "looking forward"]),
        make("experience", "Explain your professional experience", .interview, .developing, "Recruiter", "Candidate", "A recruiter asks about your last role", "Explain your responsibilities and impact with a clear example.", ["Use past tense accurately", "Name an outcome", "Connect it to the new role"], ["Use one concrete example"], ["responsible for", "delivered", "improved", "collaborated"]),
        make("difficult-question", "Answer a difficult interview question", .interview, .advanced, "Hiring manager", "Candidate", "A challenging interview follow-up", "Answer a weakness or failure question without becoming defensive.", ["Acknowledge the situation", "Explain your action", "Show what changed"], ["Avoid blaming others"], ["learned", "approach", "feedback", "improve"]),
        make("technical-clarity", "Explain a technical problem clearly", .meeting, .developing, "Non-technical manager", "Technical specialist", "A project-risk meeting", "Explain a technical blocker so a non-technical stakeholder can make a decision.", ["Use plain language", "State impact", "Ask for a decision"], ["Avoid unexplained jargon"], ["blocker", "impact", "option", "recommend"]),
        make("polite-disagreement", "Disagree politely in a meeting", .meeting, .advanced, "Project lead", "Team member", "A planning meeting", "Challenge a proposal while preserving a collaborative tone.", ["Acknowledge the idea", "State your concern", "Offer an alternative"], ["Do not say 'you are wrong'"], ["I see your point", "concern", "alternative", "trade-off"]),
        make("status-update", "Give a project status update", .meeting, .foundation, "Manager", "Project owner", "Weekly stand-up", "Give a concise update with progress, risk and next step.", ["State status", "Name one blocker", "Commit to a next action"], ["Keep it under two minutes"], ["on track", "delayed", "blocked", "next step"]),
        make("clarification", "Ask for clarification", .meeting, .foundation, "Colleague", "Team member", "An unclear work request", "Ask focused questions before accepting an ambiguous task.", ["Restate the request", "Ask about success criteria", "Confirm timing"], ["Do not pretend to understand"], ["clarify", "priority", "deadline", "success"]),
        make("dissatisfied-client", "Handle a dissatisfied client", .client, .advanced, "Dissatisfied client", "Account manager", "A client call after a missed expectation", "De-escalate the concern and agree on a credible next step.", ["Acknowledge impact", "Ask one diagnostic question", "Offer a specific follow-up"], ["Do not make promises you cannot keep"], ["understand", "frustrating", "investigate", "follow up"]),
        make("defend-decision", "Defend a decision", .meeting, .advanced, "Senior stakeholder", "Decision owner", "A review of a contested choice", "Explain reasoning, evidence and trade-offs under challenge.", ["State recommendation", "Use evidence", "Name a trade-off"], ["Stay concise under interruption"], ["recommend", "evidence", "trade-off", "mitigate"]),
        make("deadline", "Negotiate a deadline", .client, .developing, "Client or manager", "Project owner", "An unrealistic delivery request", "Negotiate scope or timing without sounding unhelpful.", ["Explain constraint", "Offer options", "Confirm agreement"], ["Never simply say no"], ["realistic", "scope", "priority", "commit"]),
        make("small-talk", "Make professional small talk", .networking, .foundation, "Industry peer", "Professional attendee", "A networking event", "Start and sustain a brief professional conversation, then close naturally.", ["Open with context", "Ask a follow-up", "Close with a next step"], ["Avoid personal assumptions"], ["what brings you", "interested in", "insight", "connect"]),
        make("present-idea", "Present an idea", .presentation, .developing, "Leadership team", "Presenter", "A short proposal pitch", "Present an idea, explain benefit and invite questions.", ["Lead with the problem", "Explain benefit", "Ask for feedback"], ["Keep one central message"], ["proposal", "benefit", "outcome", "feedback"])
    ]
    private static func make(_ id: String, _ title: String, _ category: MissionCategory, _ difficulty: MissionDifficulty, _ aiRole: String, _ userRole: String, _ situation: String, _ objective: String, _ success: [String], _ constraints: [String], _ vocabulary: [String]) -> Mission { Mission(id: id, title: title, category: category, difficulty: difficulty, aiRole: aiRole, userRole: userRole, situation: situation, objective: objective, successCriteria: success, constraints: constraints, suggestedVocabulary: vocabulary, estimatedMinutes: 6, supportsRepair: true) }
}
private extension MissionCategory { var difficultSituation: DifficultSituation { switch self { case .interview: .interviews; case .meeting: .meetings; case .presentation: .presentations; case .client: .clientCalls; case .networking: .networking } } }
